abm_materiales_new:
    path:     /new
    defaults: { _controller: CovertechdesignAdminBundle:Materiales:new }

abm_materiales_edit:
    path:     /edit/{id}
    defaults: { _controller: CovertechdesignAdminBundle:Materiales:edit }
