abm_modelos_new:
    path:     /new
    defaults: { _controller: CovertechdesignAdminBundle:Modelos:new }

abm_modelos_edit:
    path:     /edit/{id}
    defaults: { _controller: CovertechdesignAdminBundle:Modelos:edit }
